### PR TITLE
Make scripts compatible with python 3

### PR DESCRIPTION
**Pull request by pokowaka**
- Transformation done by 2to3 -w *.py
- Includes change of messaging so people doen't pass in a url vs
  zipfile.

Test: Both python2 and python3 runs succeed.

### CODE REVIEW

**Comment by 741g** [comment]
Looks good, but please update the readme to make the python 3 dependency explicit.

**Comment by 741g** [comment]
Ah, it's also compatible with 2 according to the Test. So we could probably say in the readme that both 2 and 3 should work, just so it's more clear

**Comment by pokowaka** [comment]
Added a comment in the readme..

**Comment by 741g** [comment]
Awesome, thanks!

**Pull request merged**
