### PR TITLE
Do not merge this: Make the ports configurable (adb, serial, grpc)

### LINKED ISSUE #189: On running with Singularity / full user mode
I need to run the generated docker images (the ones built with `emu-docker create`) with singularity [[1]]

[1]: https://sylabs.io/guides/3.6/user-guide/introduction.html

First thing: this is working quite well ! 

But since singularity doesn't allow port mapping when calling in user mode (/I may be wrong/), port collisions will occur when starting a second container in the same machine. 
It seems that this can be fixed by changing the ports in the `launch_emulator.sh` (console, debugger, grpc and socat ports) so I'm wondering if you'd accept to allow those ports to be parameterized by an environment variable (like ADB_KEY in the same file). We could default to the current values if the variables are unset.

### PR DESCRIPTION
**Pull request by msimonin**
Fix #189

### CODE REVIEW

**Comment by dmarjanovic** [comment]
@msimonin for my better understanding of your use case, you'd create image like e.g.:

```
export ADB_PORT=5555
export GRPC_PORT=8554
emu-docker create...
```

then in case of docker one could run container with:

```
docker run \
  -e ADBKEY="$(cat ~/.android/adbkey)" \
  --device /dev/kvm \
  --publish $GRPC_PORT:$GPRC_PIRT/tcp \
  --publish $ADB_PORT:$ADB_PORT/tcp  \
  IMAGE_ID
```

now if port envs change the same commands from above could be used to create 2nd image then run 2nd container successfully in parallel with the 1st running container. Am I on the right track?

If so, I'd suggest to parametrize `run*.sh` too with the 2 port variables to have more complete & consistent scripts. We would for sure like to play with multiple docker containers running in parallel eventually and check connected tests stability and usefulness in everyday use. Thanks

**Comment by msimonin** [comment]
Hi @dmarjanovic,

First of all I think I'll withdraw this PR, I don't think it neither solve my use case nor  what you are mentionning about running several dockers in parallel in the same machine. 

## 1. First my use case: use several Singuarity containers in parallel on the same machine

I'm using Singularity [[1]], something which can be seen as docker in user space. Roughly when running a singularity container the filesystem is chrooted but the network stack used is the host one. So there's no port mapping (at least when using in full user mode). In other words any ports open inside the container will be also open on the host system.

In this quest, my first option was to take the docker image and convert it into a singularity image [[2]]. This was appealing because all the image definition logic was reused. To avoid port collison I'd need to make sure all the ports used *inside* the container can be made unique. This is the purpose of this PR: make all the internal ports configurable as to avoid collision when running in parallel on the same host. As you mentionned, since I was focused on something else than docker I didn't changed the `run.sh` script.

[2]: https://sylabs.io/guides/3.6/user-guide/quick_start.html#download-pre-built-images

In my initial tests this was ok, but from time to time the conversion from a docker image to a singularity image seems to do weird things to the emulator disk image (e.g symbolic links broken). So I'm not happy with this PR anymore.

[1]: https://sylabs.io/guides/3.6/user-guide/

## 2. Other use case: run several docker in parallel

To solve this I think we only need to change de `run.sh` script to make the *external* ports configurable as you mentionned.
We don't need to do anything to the *internal* ports since they aren't exposed at all.


## 3. So,

For 1., I think I can build a Singularity image from a definition file [[3]]. Implementation-wise we could think about supporting another container backend (something like  a new `SingularityService` in `emu-docker`). I've quickly hacked something and the process seems to be more stable than the initial one. 
My first guess is that the changes here would be about having a singularity definition file instead (or in addition to) the Dockerfile and changing the `launch_emulator.sh` script to remove the useless `socat` calls
 
For 2., this is more straightforward.

[3]: https://sylabs.io/guides/3.6/user-guide/quick_start.html#singularity-definition-files
 

What do you think ?

**Comment by dmarjanovic** [comment]
@msimonin thanks for clarification. I suggest you proceed with 3. in a way it makes sense for you.

Currently for 2. I would be happy even without changing any scripts for now but only documenting in readme what's written in https://github.com/google/android-emulator-container-scripts/issues/72#issuecomment-559257309. I always forget that (hopefully) only the host ports should be changed in `--publish PORT_HOST:PORT_CONTAINER/tcp`. I might just do PR for that.

I'm not yet looking into concurrent containers running on the same host but that's coming on my desk soon. Based on my experience with multiple native emulators on the same host I am quite pessimistic about connected tests stability and don't expect miracles but it looks like it's worth to at least try with Docker now that we have these nice scripts.

**Comment by msimonin** [comment]
Closing as this. There's a risk that this adds too much noise in the code (to balance with the benefit of it).

**Pull request closed without merging**
